function [XCMP,cfsCMP,dimCFS] = dm_dwt(X)
% FUNC_COMPRESS_DW2D Saved Compression Process.
%   X: matrix of data
%   -----------------
%   XCMP: matrix of compressed data
%   cfsCMP: decomposition vector (see WAVEDEC2)
%   dimCFS: corresponding bookkeeping matrix

%  Auto-generated by Wavelet Toolbox on 23-Apr-2019 21:25:53

% Analysis parameters.
%---------------------
wname = 'sym8';
level = 4;

% Compression parameters.
%------------------------
% meth = 'bal_sn';
sorh = 'h';    % Specified soft or hard thresholding
thrSettings = 92.402092057507247;
roundFLAG = true;

% Compression using WDENCMP.
%--------------------------
[coefs,sizes] = wavedec2(X,level,wname);
[XCMP,cfsCMP,dimCFS] = wdencmp('gbl',coefs,sizes, ...
    wname,level,thrSettings,sorh,1);
if roundFLAG , XCMP = round(XCMP); end
if isequal(class(X),'uint8') , XCMP = uint8(XCMP); 
end
